pipeline:
  class_path: preprocessing.pipeline_downstream.DownstreamPipeline
  init_args:
    do_ica: False
    line_freqs: [50]
    lp_freq: 80
    descriptions: ['0', '1']
    tmin: -0.5
    tlen: 6.0
dataset_path: /scratch/s194260/ern_edf/
out_path: /scratch/s194260/preprocess_downstream/preprocess_downstream_ern_noica_6.0/
log_path: preprocess_downstream_ern_noica_6.0.log 
overwrite: False
shuffle_files: True
batch_size: 4
n_jobs: 16