pipeline:
  class_path: preprocessing.pipeline_downstream.DownstreamPipelineBENDR
  init_args:
    descriptions: ['Eye blinking', 'Eye movement left-right', 'Eyes closed', 'Eyes opened', 'Jaw clenching']
    tmin: -0.5
    tlen: 6.0
dataset_path: /scratch/s194260/bhutan/
out_path: /scratch/s194260/preprocess_downstream/preprocess_downstream_bhutan_bendr_6.0/
log_path: preprocess_downstream_bhutan_bendr_6.0.log 
overwrite: False
shuffle_files: True
batch_size: 4
n_jobs: 16