dataset_path: /scratch/s194260/preprocess_downstream/preprocess_downstream_BCIC_bendr_6.0_rename_combined
encoder_path: /scratch/s194260/BENDR/bendr_data/checkpoints/tuh_bendr_standardize.ckpt
name: bci_bendr_bendr_6.0_rename
n_splits: 9
batch_size: 16
num_workers: 4
num_epochs: 50
seed: 42
n_repeats: 5
device: cuda
n_device: 1
out_features: 4