dataset_path: /scratch/s194101/data/preprocessed_downstream/tuev/noica_5.0_titans_combine_test_debug_combined
encoder_path: /scratch/agjma/checkpoints/tuh-noica-standardize-epoch=9-step=68317-val_loss=0.26.ckpt
name: tuev_noica_noica_5.0_nogroups
n_splits: 10
batch_size: 16
num_workers: 4
num_epochs: 50
seed: 42
n_repeats: 2
device: cuda
n_device: 1
out_features: 6